version: '2'

services:
    api:
      build: ./SocialMedia
      restart: unless-stopped
      container_name: api
      ports:
      - "8087:8087"
      depends_on:
      - mariadb
      networks:
      - polytech
      
    mariadb:
      container_name: mariadb
      image: mariadb
      restart: on-failure
      volumes:
      - mariadb:/var/lib/mysql
      environment:
      - MYSQL_ROOT_PASSWORD=glopglop
      - MYSQL_DATABASE=auth
      - MYSQL_USER=pifou
      - MYSQL_PASSWORD=pasglop
      networks:
      - polytech

networks:
    polytech:
    
volumes:
    mariadb:
